name = "cf-web-to-markdown"
main = "src/index.ts"
compatibility_date = "2024-03-17"

[vars]
#CLOUDFLARE_ACCOUNT_ID = ""
#CLOUDFLARE_API_TOKEN = ""

[browser]
binding = "BROWSER"

[assets]
directory = "./public"
